; Generated by cxx1 for x86_64-windows, in MASM syntax for ml64.
; The instruction selection is the same one the Linux backend makes;
; only the spelling is Microsoft's. See src/backend/Masm.cpp.

OPTION DOTNAME
OPTION NOSCOPED
OPTION PROC:PRIVATE

PUBLIC ??0S@@QEAA@H@Z
PUBLIC ??1S@@QEAA@XZ
PUBLIC ?count@@YAHH@Z
PUBLIC ?inLoop@@YAHXZ
PUBLIC ?lazy@@YAH_N@Z
PUBLIC main
EXTERN _Init_thread_footer:PROC
EXTERN _Init_thread_header:PROC
EXTERN __CxxFrameHandler3:PROC
EXTERN atexit:PROC
EXTERN printf:PROC


.CONST
$_L_str_0 DB 76, 69, 68, 71, 69, 82, 32, 98, 117, 105, 108, 116, 61, 37, 100, 32
  DB 103, 111, 110, 101, 61, 37, 100, 32, 108, 105, 118, 101, 61, 37, 100, 32
  DB 100, 111, 117, 98, 108, 101, 61, 37, 100, 32, 112, 104, 97, 110, 116, 111
  DB 109, 61, 37, 100, 32, 111, 118, 101, 114, 61, 37, 100, 32, 108, 111, 115
  DB 116, 61, 37, 100, 10, 0
$_L_str_1 DB 83, 0
$_L_str_2 DB 83, 37, 100, 10, 0
$_L_str_3 DB 83, 0
$_L_str_4 DB 126, 83, 37, 100, 10, 0
$_L_str_5 DB 37, 100, 32, 37, 100, 32, 37, 100, 10, 0
$_L_str_6 DB 37, 100, 10, 0
$_L_str_7 DB 37, 100, 32, 37, 100, 32, 37, 100, 10, 0

.DATA?
  ALIGN 16
lfAddr DB 4096 DUP (?)
  ALIGN 16
lfName DB 4096 DUP (?)
  ALIGN 16
lfState DB 2048 DUP (?)
  ALIGN 4
lfBuiltCount DB 4 DUP (?)
  ALIGN 4
lfGoneCount DB 4 DUP (?)
  ALIGN 4
lfDoubleCount DB 4 DUP (?)
  ALIGN 4
lfPhantomCount DB 4 DUP (?)
  ALIGN 4
lfOverCount DB 4 DUP (?)
  ALIGN 4
lfLostCount DB 4 DUP (?)
  ALIGN 4
$?count@@YAHH@Z_s DB 4 DUP (?)
  ALIGN 4
$?count@@YAHH@Z_s$guard DB 4 DUP (?)
  ALIGN 4
$?inLoop@@YAHXZ_loop DB 4 DUP (?)
  ALIGN 4
$?inLoop@@YAHXZ_loop$guard DB 4 DUP (?)
  ALIGN 4
$?lazy@@YAH_N@Z_late DB 4 DUP (?)
  ALIGN 4
$?lazy@@YAH_N@Z_late$guard DB 4 DUP (?)

.CODE
?lfSame@@YA_NPEBD0@Z PROC
$LNbeg$?lfSame@@YA_NPEBD0@Z:
  push rbp
$LNpush$?lfSame@@YA_NPEBD0@Z:
  sub rsp, 16
$LNalloc$?lfSame@@YA_NPEBD0@Z:
  mov rbp, rsp
$LNfp$?lfSame@@YA_NPEBD0@Z:
$LNprolog$?lfSame@@YA_NPEBD0@Z:
  mov rax, rcx
  mov QWORD PTR [rbp+8], rax
  mov rax, rdx
  mov QWORD PTR [rbp], rax
$_L_?lfSame@@YA_NPEBD0@Z_begin_0:
  mov rax, 0
  push rax
  lea rax, [rbp+8]
  mov rax, QWORD PTR [rax]
  movsx rax, BYTE PTR [rax]
  movsxd rax, eax
  pop r10
  cmp eax, r10d
  setne al
  movzx rax, al
  cmp rax, 0
  je $_L_?lfSame@@YA_NPEBD0@Z_sc_1
  lea rax, [rbp]
  mov rax, QWORD PTR [rax]
  movsx rax, BYTE PTR [rax]
  movsxd rax, eax
  push rax
  lea rax, [rbp+8]
  mov rax, QWORD PTR [rax]
  movsx rax, BYTE PTR [rax]
  movsxd rax, eax
  pop r10
  cmp eax, r10d
  sete al
  movzx rax, al
  cmp rax, 0
  je $_L_?lfSame@@YA_NPEBD0@Z_sc_1
  mov rax, 1
  jmp $_L_?lfSame@@YA_NPEBD0@Z_scend_1
$_L_?lfSame@@YA_NPEBD0@Z_sc_1:
  mov rax, 0
$_L_?lfSame@@YA_NPEBD0@Z_scend_1:
  cmp rax, 0
  je $_L_?lfSame@@YA_NPEBD0@Z_end_0
  lea rax, [rbp+8]
  push rax
  mov rax, QWORD PTR [rax]
  push rax
  add rax, 1
  pop rdx
  pop r10
  mov QWORD PTR [r10], rax
  mov rax, rdx
  lea rax, [rbp]
  push rax
  mov rax, QWORD PTR [rax]
  push rax
  add rax, 1
  pop rdx
  pop r10
  mov QWORD PTR [r10], rax
  mov rax, rdx
  jmp $_L_?lfSame@@YA_NPEBD0@Z_begin_0
$_L_?lfSame@@YA_NPEBD0@Z_end_0:
  lea rax, [rbp]
  mov rax, QWORD PTR [rax]
  movsx rax, BYTE PTR [rax]
  movsxd rax, eax
  push rax
  lea rax, [rbp+8]
  mov rax, QWORD PTR [rax]
  movsx rax, BYTE PTR [rax]
  movsxd rax, eax
  pop r10
  cmp eax, r10d
  sete al
  movzx rax, al
  jmp $_L_return_?lfSame@@YA_NPEBD0@Z
  mov rax, 0
$_L_return_?lfSame@@YA_NPEBD0@Z:
  lea rsp, [rbp+16]
  pop rbp
  ret
$LNend$?lfSame@@YA_NPEBD0@Z:
?lfSame@@YA_NPEBD0@Z ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?lfSame@@YA_NPEBD0@Z DD imagerel $LNbeg$?lfSame@@YA_NPEBD0@Z
  DD imagerel $LNend$?lfSame@@YA_NPEBD0@Z
  DD imagerel $unwind$?lfSame@@YA_NPEBD0@Z
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?lfSame@@YA_NPEBD0@Z DB 01H
  DB $LNprolog$?lfSame@@YA_NPEBD0@Z-$LNbeg$?lfSame@@YA_NPEBD0@Z
  DB 3
  DB 05H
  DB $LNfp$?lfSame@@YA_NPEBD0@Z-$LNbeg$?lfSame@@YA_NPEBD0@Z
  DB 03H
  DB $LNalloc$?lfSame@@YA_NPEBD0@Z-$LNbeg$?lfSame@@YA_NPEBD0@Z
  DB 012H
  DB $LNpush$?lfSame@@YA_NPEBD0@Z-$LNbeg$?lfSame@@YA_NPEBD0@Z
  DB 050H
  DW 0
.xdata ENDS

.CODE
?lfFind@@YAHPEBXPEBD@Z PROC
$LNbeg$?lfFind@@YAHPEBXPEBD@Z:
  push rbp
$LNpush$?lfFind@@YAHPEBXPEBD@Z:
  sub rsp, 64
$LNalloc$?lfFind@@YAHPEBXPEBD@Z:
  mov rbp, rsp
$LNfp$?lfFind@@YAHPEBXPEBD@Z:
$LNprolog$?lfFind@@YAHPEBXPEBD@Z:
  mov rax, rcx
  mov QWORD PTR [rbp+56], rax
  mov rax, rdx
  mov QWORD PTR [rbp+48], rax
  mov rax, 0
  push rax
  lea rax, [rbp+44]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
$_L_?lfFind@@YAHPEBXPEBD@Z_begin_0:
  mov rax, 512
  push rax
  lea rax, [rbp+44]
  movsxd rax, DWORD PTR [rax]
  pop r10
  cmp eax, r10d
  setl al
  movzx rax, al
  cmp rax, 0
  je $_L_?lfFind@@YAHPEBXPEBD@Z_end_0
  lea rax, [rbp+56]
  mov rax, QWORD PTR [rax]
  push rax
  mov rax, 8
  push rax
  lea rax, [rbp+44]
  movsxd rax, DWORD PTR [rax]
  pop r10
  imul rax, r10
  push rax
  lea rax, [lfAddr]
  pop r10
  add rax, r10
  mov rax, QWORD PTR [rax]
  pop r10
  cmp rax, r10
  sete al
  movzx rax, al
  cmp rax, 0
  je $_L_?lfFind@@YAHPEBXPEBD@Z_sc_2
  mov rax, 8
  push rax
  lea rax, [rbp+44]
  movsxd rax, DWORD PTR [rax]
  pop r10
  imul rax, r10
  push rax
  lea rax, [lfName]
  pop r10
  add rax, r10
  mov rax, QWORD PTR [rax]
  push rax
  lea rax, [rbp+48]
  mov rax, QWORD PTR [rax]
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call ?lfSame@@YA_NPEBD0@Z
  movzx rax, al
  cmp rax, 0
  je $_L_?lfFind@@YAHPEBXPEBD@Z_sc_2
  mov rax, 1
  jmp $_L_?lfFind@@YAHPEBXPEBD@Z_scend_2
$_L_?lfFind@@YAHPEBXPEBD@Z_sc_2:
  mov rax, 0
$_L_?lfFind@@YAHPEBXPEBD@Z_scend_2:
  cmp rax, 0
  je $_L_?lfFind@@YAHPEBXPEBD@Z_end_1
  lea rax, [rbp+44]
  movsxd rax, DWORD PTR [rax]
  jmp $_L_return_?lfFind@@YAHPEBXPEBD@Z
$_L_?lfFind@@YAHPEBXPEBD@Z_end_1:
$_L_?lfFind@@YAHPEBXPEBD@Z_step_0:
  lea rax, [rbp+44]
  push rax
  movsxd rax, DWORD PTR [rax]
  push rax
  add rax, 1
  pop rdx
  pop r10
  mov DWORD PTR [r10], eax
  mov rax, rdx
  jmp $_L_?lfFind@@YAHPEBXPEBD@Z_begin_0
$_L_?lfFind@@YAHPEBXPEBD@Z_end_0:
  mov rax, 1
  neg eax
  movsxd rax, eax
  jmp $_L_return_?lfFind@@YAHPEBXPEBD@Z
  mov rax, 0
$_L_return_?lfFind@@YAHPEBXPEBD@Z:
  lea rsp, [rbp+64]
  pop rbp
  ret
$LNend$?lfFind@@YAHPEBXPEBD@Z:
?lfFind@@YAHPEBXPEBD@Z ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?lfFind@@YAHPEBXPEBD@Z DD imagerel $LNbeg$?lfFind@@YAHPEBXPEBD@Z
  DD imagerel $LNend$?lfFind@@YAHPEBXPEBD@Z
  DD imagerel $unwind$?lfFind@@YAHPEBXPEBD@Z
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?lfFind@@YAHPEBXPEBD@Z DB 01H
  DB $LNprolog$?lfFind@@YAHPEBXPEBD@Z-$LNbeg$?lfFind@@YAHPEBXPEBD@Z
  DB 3
  DB 05H
  DB $LNfp$?lfFind@@YAHPEBXPEBD@Z-$LNbeg$?lfFind@@YAHPEBXPEBD@Z
  DB 03H
  DB $LNalloc$?lfFind@@YAHPEBXPEBD@Z-$LNbeg$?lfFind@@YAHPEBXPEBD@Z
  DB 072H
  DB $LNpush$?lfFind@@YAHPEBXPEBD@Z-$LNbeg$?lfFind@@YAHPEBXPEBD@Z
  DB 050H
  DW 0
.xdata ENDS

.CODE
?lfBuilt@@YAXPEBXPEBD@Z PROC
$LNbeg$?lfBuilt@@YAXPEBXPEBD@Z:
  push rbp
$LNpush$?lfBuilt@@YAXPEBXPEBD@Z:
  sub rsp, 64
$LNalloc$?lfBuilt@@YAXPEBXPEBD@Z:
  mov rbp, rsp
$LNfp$?lfBuilt@@YAXPEBXPEBD@Z:
$LNprolog$?lfBuilt@@YAXPEBXPEBD@Z:
  mov rax, rcx
  mov QWORD PTR [rbp+56], rax
  mov rax, rdx
  mov QWORD PTR [rbp+48], rax
  lea rax, [lfBuiltCount]
  push rax
  movsxd rax, DWORD PTR [rax]
  push rax
  add rax, 1
  pop rdx
  pop r10
  mov DWORD PTR [r10], eax
  mov rax, rdx
  lea rax, [rbp+56]
  mov rax, QWORD PTR [rax]
  push rax
  lea rax, [rbp+48]
  mov rax, QWORD PTR [rax]
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call ?lfFind@@YAHPEBXPEBD@Z
  movsxd rax, eax
  push rax
  lea rax, [rbp+44]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  mov rax, 0
  push rax
  lea rax, [rbp+44]
  movsxd rax, DWORD PTR [rax]
  pop r10
  cmp eax, r10d
  setge al
  movzx rax, al
  cmp rax, 0
  je $_L_?lfBuilt@@YAXPEBXPEBD@Z_end_0
  mov rax, 1
  push rax
  mov rax, 4
  push rax
  lea rax, [rbp+44]
  movsxd rax, DWORD PTR [rax]
  pop r10
  imul rax, r10
  push rax
  lea rax, [lfState]
  pop r10
  add rax, r10
  movsxd rax, DWORD PTR [rax]
  pop r10
  cmp eax, r10d
  sete al
  movzx rax, al
  cmp rax, 0
  je $_L_?lfBuilt@@YAXPEBXPEBD@Z_end_1
  lea rax, [lfOverCount]
  push rax
  movsxd rax, DWORD PTR [rax]
  push rax
  add rax, 1
  pop rdx
  pop r10
  mov DWORD PTR [r10], eax
  mov rax, rdx
$_L_?lfBuilt@@YAXPEBXPEBD@Z_end_1:
  mov rax, 1
  push rax
  mov rax, 4
  push rax
  lea rax, [rbp+44]
  movsxd rax, DWORD PTR [rax]
  pop r10
  imul rax, r10
  push rax
  lea rax, [lfState]
  pop r10
  add rax, r10
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  jmp $_L_return_?lfBuilt@@YAXPEBXPEBD@Z
$_L_?lfBuilt@@YAXPEBXPEBD@Z_end_0:
  mov rax, 0
  push rax
  lea rax, [rbp+40]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
$_L_?lfBuilt@@YAXPEBXPEBD@Z_begin_2:
  mov rax, 512
  push rax
  lea rax, [rbp+40]
  movsxd rax, DWORD PTR [rax]
  pop r10
  cmp eax, r10d
  setl al
  movzx rax, al
  cmp rax, 0
  je $_L_?lfBuilt@@YAXPEBXPEBD@Z_end_2
  mov rax, 0
  push rax
  mov rax, 8
  push rax
  lea rax, [rbp+40]
  movsxd rax, DWORD PTR [rax]
  pop r10
  imul rax, r10
  push rax
  lea rax, [lfAddr]
  pop r10
  add rax, r10
  mov rax, QWORD PTR [rax]
  pop r10
  cmp rax, r10
  sete al
  movzx rax, al
  cmp rax, 0
  je $_L_?lfBuilt@@YAXPEBXPEBD@Z_end_3
  lea rax, [rbp+56]
  mov rax, QWORD PTR [rax]
  push rax
  mov rax, 8
  push rax
  lea rax, [rbp+40]
  movsxd rax, DWORD PTR [rax]
  pop r10
  imul rax, r10
  push rax
  lea rax, [lfAddr]
  pop r10
  add rax, r10
  mov r10, rax
  pop rax
  mov QWORD PTR [r10], rax
  lea rax, [rbp+48]
  mov rax, QWORD PTR [rax]
  push rax
  mov rax, 8
  push rax
  lea rax, [rbp+40]
  movsxd rax, DWORD PTR [rax]
  pop r10
  imul rax, r10
  push rax
  lea rax, [lfName]
  pop r10
  add rax, r10
  mov r10, rax
  pop rax
  mov QWORD PTR [r10], rax
  mov rax, 1
  push rax
  mov rax, 4
  push rax
  lea rax, [rbp+40]
  movsxd rax, DWORD PTR [rax]
  pop r10
  imul rax, r10
  push rax
  lea rax, [lfState]
  pop r10
  add rax, r10
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  jmp $_L_return_?lfBuilt@@YAXPEBXPEBD@Z
$_L_?lfBuilt@@YAXPEBXPEBD@Z_end_3:
$_L_?lfBuilt@@YAXPEBXPEBD@Z_step_2:
  lea rax, [rbp+40]
  push rax
  movsxd rax, DWORD PTR [rax]
  push rax
  add rax, 1
  pop rdx
  pop r10
  mov DWORD PTR [r10], eax
  mov rax, rdx
  jmp $_L_?lfBuilt@@YAXPEBXPEBD@Z_begin_2
$_L_?lfBuilt@@YAXPEBXPEBD@Z_end_2:
  lea rax, [lfLostCount]
  push rax
  movsxd rax, DWORD PTR [rax]
  push rax
  add rax, 1
  pop rdx
  pop r10
  mov DWORD PTR [r10], eax
  mov rax, rdx
  mov rax, 0
$_L_return_?lfBuilt@@YAXPEBXPEBD@Z:
  lea rsp, [rbp+64]
  pop rbp
  ret
$LNend$?lfBuilt@@YAXPEBXPEBD@Z:
?lfBuilt@@YAXPEBXPEBD@Z ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?lfBuilt@@YAXPEBXPEBD@Z DD imagerel $LNbeg$?lfBuilt@@YAXPEBXPEBD@Z
  DD imagerel $LNend$?lfBuilt@@YAXPEBXPEBD@Z
  DD imagerel $unwind$?lfBuilt@@YAXPEBXPEBD@Z
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?lfBuilt@@YAXPEBXPEBD@Z DB 01H
  DB $LNprolog$?lfBuilt@@YAXPEBXPEBD@Z-$LNbeg$?lfBuilt@@YAXPEBXPEBD@Z
  DB 3
  DB 05H
  DB $LNfp$?lfBuilt@@YAXPEBXPEBD@Z-$LNbeg$?lfBuilt@@YAXPEBXPEBD@Z
  DB 03H
  DB $LNalloc$?lfBuilt@@YAXPEBXPEBD@Z-$LNbeg$?lfBuilt@@YAXPEBXPEBD@Z
  DB 072H
  DB $LNpush$?lfBuilt@@YAXPEBXPEBD@Z-$LNbeg$?lfBuilt@@YAXPEBXPEBD@Z
  DB 050H
  DW 0
.xdata ENDS

.CODE
?lfGone@@YAXPEBXPEBD@Z PROC
$LNbeg$?lfGone@@YAXPEBXPEBD@Z:
  push rbp
$LNpush$?lfGone@@YAXPEBXPEBD@Z:
  sub rsp, 64
$LNalloc$?lfGone@@YAXPEBXPEBD@Z:
  mov rbp, rsp
$LNfp$?lfGone@@YAXPEBXPEBD@Z:
$LNprolog$?lfGone@@YAXPEBXPEBD@Z:
  mov rax, rcx
  mov QWORD PTR [rbp+56], rax
  mov rax, rdx
  mov QWORD PTR [rbp+48], rax
  lea rax, [rbp+56]
  mov rax, QWORD PTR [rax]
  push rax
  lea rax, [rbp+48]
  mov rax, QWORD PTR [rax]
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call ?lfFind@@YAHPEBXPEBD@Z
  movsxd rax, eax
  push rax
  lea rax, [rbp+44]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  mov rax, 0
  push rax
  lea rax, [rbp+44]
  movsxd rax, DWORD PTR [rax]
  pop r10
  cmp eax, r10d
  setl al
  movzx rax, al
  cmp rax, 0
  je $_L_?lfGone@@YAXPEBXPEBD@Z_end_0
  lea rax, [lfPhantomCount]
  push rax
  movsxd rax, DWORD PTR [rax]
  push rax
  add rax, 1
  pop rdx
  pop r10
  mov DWORD PTR [r10], eax
  mov rax, rdx
  jmp $_L_return_?lfGone@@YAXPEBXPEBD@Z
$_L_?lfGone@@YAXPEBXPEBD@Z_end_0:
  mov rax, 2
  push rax
  mov rax, 4
  push rax
  lea rax, [rbp+44]
  movsxd rax, DWORD PTR [rax]
  pop r10
  imul rax, r10
  push rax
  lea rax, [lfState]
  pop r10
  add rax, r10
  movsxd rax, DWORD PTR [rax]
  pop r10
  cmp eax, r10d
  sete al
  movzx rax, al
  cmp rax, 0
  je $_L_?lfGone@@YAXPEBXPEBD@Z_end_1
  lea rax, [lfDoubleCount]
  push rax
  movsxd rax, DWORD PTR [rax]
  push rax
  add rax, 1
  pop rdx
  pop r10
  mov DWORD PTR [r10], eax
  mov rax, rdx
  jmp $_L_return_?lfGone@@YAXPEBXPEBD@Z
$_L_?lfGone@@YAXPEBXPEBD@Z_end_1:
  mov rax, 2
  push rax
  mov rax, 4
  push rax
  lea rax, [rbp+44]
  movsxd rax, DWORD PTR [rax]
  pop r10
  imul rax, r10
  push rax
  lea rax, [lfState]
  pop r10
  add rax, r10
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  lea rax, [lfGoneCount]
  push rax
  movsxd rax, DWORD PTR [rax]
  push rax
  add rax, 1
  pop rdx
  pop r10
  mov DWORD PTR [r10], eax
  mov rax, rdx
  mov rax, 0
$_L_return_?lfGone@@YAXPEBXPEBD@Z:
  lea rsp, [rbp+64]
  pop rbp
  ret
$LNend$?lfGone@@YAXPEBXPEBD@Z:
?lfGone@@YAXPEBXPEBD@Z ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?lfGone@@YAXPEBXPEBD@Z DD imagerel $LNbeg$?lfGone@@YAXPEBXPEBD@Z
  DD imagerel $LNend$?lfGone@@YAXPEBXPEBD@Z
  DD imagerel $unwind$?lfGone@@YAXPEBXPEBD@Z
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?lfGone@@YAXPEBXPEBD@Z DB 01H
  DB $LNprolog$?lfGone@@YAXPEBXPEBD@Z-$LNbeg$?lfGone@@YAXPEBXPEBD@Z
  DB 3
  DB 05H
  DB $LNfp$?lfGone@@YAXPEBXPEBD@Z-$LNbeg$?lfGone@@YAXPEBXPEBD@Z
  DB 03H
  DB $LNalloc$?lfGone@@YAXPEBXPEBD@Z-$LNbeg$?lfGone@@YAXPEBXPEBD@Z
  DB 072H
  DB $LNpush$?lfGone@@YAXPEBXPEBD@Z-$LNbeg$?lfGone@@YAXPEBXPEBD@Z
  DB 050H
  DW 0
.xdata ENDS

.CODE
?lfLive@@YAHXZ PROC
$LNbeg$?lfLive@@YAHXZ:
  push rbp
$LNpush$?lfLive@@YAHXZ:
  sub rsp, 16
$LNalloc$?lfLive@@YAHXZ:
  mov rbp, rsp
$LNfp$?lfLive@@YAHXZ:
$LNprolog$?lfLive@@YAHXZ:
  mov rax, 0
  push rax
  lea rax, [rbp+12]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  mov rax, 0
  push rax
  lea rax, [rbp+8]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
$_L_?lfLive@@YAHXZ_begin_0:
  mov rax, 512
  push rax
  lea rax, [rbp+8]
  movsxd rax, DWORD PTR [rax]
  pop r10
  cmp eax, r10d
  setl al
  movzx rax, al
  cmp rax, 0
  je $_L_?lfLive@@YAHXZ_end_0
  mov rax, 1
  push rax
  mov rax, 4
  push rax
  lea rax, [rbp+8]
  movsxd rax, DWORD PTR [rax]
  pop r10
  imul rax, r10
  push rax
  lea rax, [lfState]
  pop r10
  add rax, r10
  movsxd rax, DWORD PTR [rax]
  pop r10
  cmp eax, r10d
  sete al
  movzx rax, al
  cmp rax, 0
  je $_L_?lfLive@@YAHXZ_end_1
  lea rax, [rbp+12]
  push rax
  movsxd rax, DWORD PTR [rax]
  push rax
  add rax, 1
  pop rdx
  pop r10
  mov DWORD PTR [r10], eax
  mov rax, rdx
$_L_?lfLive@@YAHXZ_end_1:
$_L_?lfLive@@YAHXZ_step_0:
  lea rax, [rbp+8]
  push rax
  movsxd rax, DWORD PTR [rax]
  push rax
  add rax, 1
  pop rdx
  pop r10
  mov DWORD PTR [r10], eax
  mov rax, rdx
  jmp $_L_?lfLive@@YAHXZ_begin_0
$_L_?lfLive@@YAHXZ_end_0:
  lea rax, [rbp+12]
  movsxd rax, DWORD PTR [rax]
  jmp $_L_return_?lfLive@@YAHXZ
  mov rax, 0
$_L_return_?lfLive@@YAHXZ:
  lea rsp, [rbp+16]
  pop rbp
  ret
$LNend$?lfLive@@YAHXZ:
?lfLive@@YAHXZ ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?lfLive@@YAHXZ DD imagerel $LNbeg$?lfLive@@YAHXZ
  DD imagerel $LNend$?lfLive@@YAHXZ
  DD imagerel $unwind$?lfLive@@YAHXZ
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?lfLive@@YAHXZ DB 01H
  DB $LNprolog$?lfLive@@YAHXZ-$LNbeg$?lfLive@@YAHXZ
  DB 3
  DB 05H
  DB $LNfp$?lfLive@@YAHXZ-$LNbeg$?lfLive@@YAHXZ
  DB 03H
  DB $LNalloc$?lfLive@@YAHXZ-$LNbeg$?lfLive@@YAHXZ
  DB 012H
  DB $LNpush$?lfLive@@YAHXZ-$LNbeg$?lfLive@@YAHXZ
  DB 050H
  DW 0
.xdata ENDS

.CODE
?lfReport@@YAXXZ PROC
$LNbeg$?lfReport@@YAXXZ:
  push rbp
$LNpush$?lfReport@@YAXXZ:
  sub rsp, 64
$LNalloc$?lfReport@@YAXXZ:
  mov rbp, rsp
$LNfp$?lfReport@@YAXXZ:
$LNprolog$?lfReport@@YAXXZ:
  lea rax, [lfLostCount]
  movsxd rax, DWORD PTR [rax]
  mov [rsp+56], rax
  lea rax, [lfOverCount]
  movsxd rax, DWORD PTR [rax]
  mov [rsp+48], rax
  lea rax, [lfPhantomCount]
  movsxd rax, DWORD PTR [rax]
  mov [rsp+40], rax
  lea rax, [lfDoubleCount]
  movsxd rax, DWORD PTR [rax]
  mov [rsp+32], rax
  lea rax, [$_L_str_0]
  push rax
  lea rax, [lfBuiltCount]
  movsxd rax, DWORD PTR [rax]
  push rax
  lea rax, [lfGoneCount]
  movsxd rax, DWORD PTR [rax]
  push rax
  sub rsp, 8
  mov rax, 0
  sub rsp, 32
  call ?lfLive@@YAHXZ
  add rsp, 40
  movsxd rax, eax
  push rax
  pop r9
  pop r8
  pop rdx
  pop rcx
  mov rax, 0
  call printf
  movsxd rax, eax
  mov rax, 0
$_L_return_?lfReport@@YAXXZ:
  lea rsp, [rbp+64]
  pop rbp
  ret
$LNend$?lfReport@@YAXXZ:
?lfReport@@YAXXZ ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?lfReport@@YAXXZ DD imagerel $LNbeg$?lfReport@@YAXXZ
  DD imagerel $LNend$?lfReport@@YAXXZ
  DD imagerel $unwind$?lfReport@@YAXXZ
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?lfReport@@YAXXZ DB 01H
  DB $LNprolog$?lfReport@@YAXXZ-$LNbeg$?lfReport@@YAXXZ
  DB 3
  DB 05H
  DB $LNfp$?lfReport@@YAXXZ-$LNbeg$?lfReport@@YAXXZ
  DB 03H
  DB $LNalloc$?lfReport@@YAXXZ-$LNbeg$?lfReport@@YAXXZ
  DB 072H
  DB $LNpush$?lfReport@@YAXXZ-$LNbeg$?lfReport@@YAXXZ
  DB 050H
  DW 0
.xdata ENDS

.CODE
?lfWatch@@YAXXZ PROC
$LNbeg$?lfWatch@@YAXXZ:
  push rbp
$LNpush$?lfWatch@@YAXXZ:
  sub rsp, 32
$LNalloc$?lfWatch@@YAXXZ:
  mov rbp, rsp
$LNfp$?lfWatch@@YAXXZ:
$LNprolog$?lfWatch@@YAXXZ:
  lea rax, [?lfReport@@YAXXZ]
  push rax
  pop rcx
  mov rax, 0
  call atexit
  movsxd rax, eax
  mov rax, 0
$_L_return_?lfWatch@@YAXXZ:
  lea rsp, [rbp+32]
  pop rbp
  ret
$LNend$?lfWatch@@YAXXZ:
?lfWatch@@YAXXZ ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?lfWatch@@YAXXZ DD imagerel $LNbeg$?lfWatch@@YAXXZ
  DD imagerel $LNend$?lfWatch@@YAXXZ
  DD imagerel $unwind$?lfWatch@@YAXXZ
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?lfWatch@@YAXXZ DB 01H
  DB $LNprolog$?lfWatch@@YAXXZ-$LNbeg$?lfWatch@@YAXXZ
  DB 3
  DB 05H
  DB $LNfp$?lfWatch@@YAXXZ-$LNbeg$?lfWatch@@YAXXZ
  DB 03H
  DB $LNalloc$?lfWatch@@YAXXZ-$LNbeg$?lfWatch@@YAXXZ
  DB 032H
  DB $LNpush$?lfWatch@@YAXXZ-$LNbeg$?lfWatch@@YAXXZ
  DB 050H
  DW 0
.xdata ENDS

.CODE
??0S@@QEAA@H@Z PROC
$LNbeg$??0S@@QEAA@H@Z:
  push rbp
$LNpush$??0S@@QEAA@H@Z:
  sub rsp, 48
$LNalloc$??0S@@QEAA@H@Z:
  mov rbp, rsp
$LNfp$??0S@@QEAA@H@Z:
$LNprolog$??0S@@QEAA@H@Z:
  mov rax, rcx
  mov QWORD PTR [rbp+32], rax
  mov rax, rdx
  mov DWORD PTR [rbp+44], eax
  lea rax, [rbp+44]
  movsxd rax, DWORD PTR [rax]
  push rax
  lea rax, [rbp+32]
  mov rax, QWORD PTR [rax]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  lea rax, [rbp+32]
  mov rax, QWORD PTR [rax]
  push rax
  lea rax, [$_L_str_1]
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call ?lfBuilt@@YAXPEBXPEBD@Z
  lea rax, [$_L_str_2]
  push rax
  lea rax, [rbp+32]
  mov rax, QWORD PTR [rax]
  movsxd rax, DWORD PTR [rax]
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call printf
  movsxd rax, eax
  mov rax, 0
$_L_return_??0S@@QEAA@H@Z:
  mov rax, [rbp+32]
  lea rsp, [rbp+48]
  pop rbp
  ret
$LNend$??0S@@QEAA@H@Z:
??0S@@QEAA@H@Z ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$??0S@@QEAA@H@Z DD imagerel $LNbeg$??0S@@QEAA@H@Z
  DD imagerel $LNend$??0S@@QEAA@H@Z
  DD imagerel $unwind$??0S@@QEAA@H@Z
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$??0S@@QEAA@H@Z DB 01H
  DB $LNprolog$??0S@@QEAA@H@Z-$LNbeg$??0S@@QEAA@H@Z
  DB 3
  DB 05H
  DB $LNfp$??0S@@QEAA@H@Z-$LNbeg$??0S@@QEAA@H@Z
  DB 03H
  DB $LNalloc$??0S@@QEAA@H@Z-$LNbeg$??0S@@QEAA@H@Z
  DB 052H
  DB $LNpush$??0S@@QEAA@H@Z-$LNbeg$??0S@@QEAA@H@Z
  DB 050H
  DW 0
.xdata ENDS

.CODE
??1S@@QEAA@XZ PROC
$LNbeg$??1S@@QEAA@XZ:
  push rbp
$LNpush$??1S@@QEAA@XZ:
  sub rsp, 48
$LNalloc$??1S@@QEAA@XZ:
  mov rbp, rsp
$LNfp$??1S@@QEAA@XZ:
$LNprolog$??1S@@QEAA@XZ:
  mov rax, rcx
  mov QWORD PTR [rbp+40], rax
  lea rax, [rbp+40]
  mov rax, QWORD PTR [rax]
  push rax
  lea rax, [$_L_str_3]
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call ?lfGone@@YAXPEBXPEBD@Z
  lea rax, [$_L_str_4]
  push rax
  lea rax, [rbp+40]
  mov rax, QWORD PTR [rax]
  movsxd rax, DWORD PTR [rax]
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call printf
  movsxd rax, eax
  mov rax, 0
$_L_return_??1S@@QEAA@XZ:
  lea rsp, [rbp+48]
  pop rbp
  ret
$LNend$??1S@@QEAA@XZ:
??1S@@QEAA@XZ ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$??1S@@QEAA@XZ DD imagerel $LNbeg$??1S@@QEAA@XZ
  DD imagerel $LNend$??1S@@QEAA@XZ
  DD imagerel $unwind$??1S@@QEAA@XZ
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$??1S@@QEAA@XZ DB 01H
  DB $LNprolog$??1S@@QEAA@XZ-$LNbeg$??1S@@QEAA@XZ
  DB 3
  DB 05H
  DB $LNfp$??1S@@QEAA@XZ-$LNbeg$??1S@@QEAA@XZ
  DB 03H
  DB $LNalloc$??1S@@QEAA@XZ-$LNbeg$??1S@@QEAA@XZ
  DB 052H
  DB $LNpush$??1S@@QEAA@XZ-$LNbeg$??1S@@QEAA@XZ
  DB 050H
  DW 0
.xdata ENDS

.CODE
??__Fs@?1??count@@YAHH@Z@YAXXZ PROC
$LNbeg$??__Fs@?1??count@@YAHH@Z@YAXXZ:
  push rbp
$LNpush$??__Fs@?1??count@@YAHH@Z@YAXXZ:
  sub rsp, 32
$LNalloc$??__Fs@?1??count@@YAHH@Z@YAXXZ:
  mov rbp, rsp
$LNfp$??__Fs@?1??count@@YAHH@Z@YAXXZ:
$LNprolog$??__Fs@?1??count@@YAHH@Z@YAXXZ:
  lea rax, [$?count@@YAHH@Z_s]
  push rax
  pop rcx
  mov rax, 0
  call ??1S@@QEAA@XZ
  mov rax, 0
$_L_return_??__Fs@?1??count@@YAHH@Z@YAXXZ:
  lea rsp, [rbp+32]
  pop rbp
  ret
$LNend$??__Fs@?1??count@@YAHH@Z@YAXXZ:
??__Fs@?1??count@@YAHH@Z@YAXXZ ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$??__Fs@?1??count@@YAHH@Z@YAXXZ DD imagerel $LNbeg$??__Fs@?1??count@@YAHH@Z@YAXXZ
  DD imagerel $LNend$??__Fs@?1??count@@YAHH@Z@YAXXZ
  DD imagerel $unwind$??__Fs@?1??count@@YAHH@Z@YAXXZ
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$??__Fs@?1??count@@YAHH@Z@YAXXZ DB 01H
  DB $LNprolog$??__Fs@?1??count@@YAHH@Z@YAXXZ-$LNbeg$??__Fs@?1??count@@YAHH@Z@YAXXZ
  DB 3
  DB 05H
  DB $LNfp$??__Fs@?1??count@@YAHH@Z@YAXXZ-$LNbeg$??__Fs@?1??count@@YAHH@Z@YAXXZ
  DB 03H
  DB $LNalloc$??__Fs@?1??count@@YAHH@Z@YAXXZ-$LNbeg$??__Fs@?1??count@@YAHH@Z@YAXXZ
  DB 032H
  DB $LNpush$??__Fs@?1??count@@YAHH@Z@YAXXZ-$LNbeg$??__Fs@?1??count@@YAHH@Z@YAXXZ
  DB 050H
  DW 0
.xdata ENDS

.CODE
?count@@YAHH@Z PROC
$LNbeg$?count@@YAHH@Z:
  push rbp
$LNpush$?count@@YAHH@Z:
  sub rsp, 48
$LNalloc$?count@@YAHH@Z:
  mov rbp, rsp
$LNfp$?count@@YAHH@Z:
$LNprolog$?count@@YAHH@Z:
  mov rax, rcx
  mov DWORD PTR [rbp+44], eax
  lea rax, [$?count@@YAHH@Z_s$guard]
  push rax
  pop rcx
  mov rax, 0
  call _Init_thread_header
  mov rax, -1
  push rax
  lea rax, [$?count@@YAHH@Z_s$guard]
  movsxd rax, DWORD PTR [rax]
  pop r10
  cmp eax, r10d
  sete al
  movzx rax, al
  cmp rax, 0
  je $_L_?count@@YAHH@Z_end_0
  lea rax, [$?count@@YAHH@Z_s]
  push rax
  lea rax, [rbp+44]
  movsxd rax, DWORD PTR [rax]
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call ??0S@@QEAA@H@Z
  lea rax, [??__Fs@?1??count@@YAHH@Z@YAXXZ]
  push rax
  pop rcx
  mov rax, 0
  call atexit
  movsxd rax, eax
  lea rax, [$?count@@YAHH@Z_s$guard]
  push rax
  pop rcx
  mov rax, 0
  call _Init_thread_footer
$_L_?count@@YAHH@Z_end_0:
  lea rax, [$?count@@YAHH@Z_s]
  push rax
  movsxd rax, DWORD PTR [rax]
  push rax
  add rax, 1
  pop rdx
  pop r10
  mov DWORD PTR [r10], eax
  mov rax, rdx
  lea rax, [$?count@@YAHH@Z_s]
  movsxd rax, DWORD PTR [rax]
  jmp $_L_return_?count@@YAHH@Z
  mov rax, 0
$_L_return_?count@@YAHH@Z:
  lea rsp, [rbp+48]
  pop rbp
  ret
$LNend$?count@@YAHH@Z:
?count@@YAHH@Z ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?count@@YAHH@Z DD imagerel $LNbeg$?count@@YAHH@Z
  DD imagerel $LNend$?count@@YAHH@Z
  DD imagerel $unwind$?count@@YAHH@Z
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?count@@YAHH@Z DB 01H
  DB $LNprolog$?count@@YAHH@Z-$LNbeg$?count@@YAHH@Z
  DB 3
  DB 05H
  DB $LNfp$?count@@YAHH@Z-$LNbeg$?count@@YAHH@Z
  DB 03H
  DB $LNalloc$?count@@YAHH@Z-$LNbeg$?count@@YAHH@Z
  DB 052H
  DB $LNpush$?count@@YAHH@Z-$LNbeg$?count@@YAHH@Z
  DB 050H
  DW 0
.xdata ENDS

.CODE
??__Floop@?1??inLoop@@YAHXZ@YAXXZ PROC
$LNbeg$??__Floop@?1??inLoop@@YAHXZ@YAXXZ:
  push rbp
$LNpush$??__Floop@?1??inLoop@@YAHXZ@YAXXZ:
  sub rsp, 32
$LNalloc$??__Floop@?1??inLoop@@YAHXZ@YAXXZ:
  mov rbp, rsp
$LNfp$??__Floop@?1??inLoop@@YAHXZ@YAXXZ:
$LNprolog$??__Floop@?1??inLoop@@YAHXZ@YAXXZ:
  lea rax, [$?inLoop@@YAHXZ_loop]
  push rax
  pop rcx
  mov rax, 0
  call ??1S@@QEAA@XZ
  mov rax, 0
$_L_return_??__Floop@?1??inLoop@@YAHXZ@YAXXZ:
  lea rsp, [rbp+32]
  pop rbp
  ret
$LNend$??__Floop@?1??inLoop@@YAHXZ@YAXXZ:
??__Floop@?1??inLoop@@YAHXZ@YAXXZ ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$??__Floop@?1??inLoop@@YAHXZ@YAXXZ DD imagerel $LNbeg$??__Floop@?1??inLoop@@YAHXZ@YAXXZ
  DD imagerel $LNend$??__Floop@?1??inLoop@@YAHXZ@YAXXZ
  DD imagerel $unwind$??__Floop@?1??inLoop@@YAHXZ@YAXXZ
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$??__Floop@?1??inLoop@@YAHXZ@YAXXZ DB 01H
  DB $LNprolog$??__Floop@?1??inLoop@@YAHXZ@YAXXZ-$LNbeg$??__Floop@?1??inLoop@@YAHXZ@YAXXZ
  DB 3
  DB 05H
  DB $LNfp$??__Floop@?1??inLoop@@YAHXZ@YAXXZ-$LNbeg$??__Floop@?1??inLoop@@YAHXZ@YAXXZ
  DB 03H
  DB $LNalloc$??__Floop@?1??inLoop@@YAHXZ@YAXXZ-$LNbeg$??__Floop@?1??inLoop@@YAHXZ@YAXXZ
  DB 032H
  DB $LNpush$??__Floop@?1??inLoop@@YAHXZ@YAXXZ-$LNbeg$??__Floop@?1??inLoop@@YAHXZ@YAXXZ
  DB 050H
  DW 0
.xdata ENDS

.CODE
?inLoop@@YAHXZ PROC
$LNbeg$?inLoop@@YAHXZ:
  push rbp
$LNpush$?inLoop@@YAHXZ:
  sub rsp, 48
$LNalloc$?inLoop@@YAHXZ:
  mov rbp, rsp
$LNfp$?inLoop@@YAHXZ:
$LNprolog$?inLoop@@YAHXZ:
  mov rax, 0
  push rax
  lea rax, [rbp+44]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  mov rax, 0
  push rax
  lea rax, [rbp+40]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
$_L_?inLoop@@YAHXZ_begin_0:
  mov rax, 3
  push rax
  lea rax, [rbp+40]
  movsxd rax, DWORD PTR [rax]
  pop r10
  cmp eax, r10d
  setl al
  movzx rax, al
  cmp rax, 0
  je $_L_?inLoop@@YAHXZ_end_0
  lea rax, [$?inLoop@@YAHXZ_loop$guard]
  push rax
  pop rcx
  mov rax, 0
  call _Init_thread_header
  mov rax, -1
  push rax
  lea rax, [$?inLoop@@YAHXZ_loop$guard]
  movsxd rax, DWORD PTR [rax]
  pop r10
  cmp eax, r10d
  sete al
  movzx rax, al
  cmp rax, 0
  je $_L_?inLoop@@YAHXZ_end_1
  lea rax, [$?inLoop@@YAHXZ_loop]
  push rax
  mov rax, 100
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call ??0S@@QEAA@H@Z
  lea rax, [??__Floop@?1??inLoop@@YAHXZ@YAXXZ]
  push rax
  pop rcx
  mov rax, 0
  call atexit
  movsxd rax, eax
  lea rax, [$?inLoop@@YAHXZ_loop$guard]
  push rax
  pop rcx
  mov rax, 0
  call _Init_thread_footer
$_L_?inLoop@@YAHXZ_end_1:
  lea rax, [rbp+40]
  movsxd rax, DWORD PTR [rax]
  push rax
  lea rax, [$?inLoop@@YAHXZ_loop]
  movsxd rax, DWORD PTR [rax]
  pop r10
  add eax, r10d
  movsxd rax, eax
  push rax
  lea rax, [$?inLoop@@YAHXZ_loop]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  lea rax, [$?inLoop@@YAHXZ_loop]
  movsxd rax, DWORD PTR [rax]
  push rax
  lea rax, [rbp+44]
  movsxd rax, DWORD PTR [rax]
  pop r10
  add eax, r10d
  movsxd rax, eax
  push rax
  lea rax, [rbp+44]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
$_L_?inLoop@@YAHXZ_step_0:
  lea rax, [rbp+40]
  push rax
  movsxd rax, DWORD PTR [rax]
  push rax
  add rax, 1
  pop rdx
  pop r10
  mov DWORD PTR [r10], eax
  mov rax, rdx
  jmp $_L_?inLoop@@YAHXZ_begin_0
$_L_?inLoop@@YAHXZ_end_0:
  lea rax, [rbp+44]
  movsxd rax, DWORD PTR [rax]
  jmp $_L_return_?inLoop@@YAHXZ
  mov rax, 0
$_L_return_?inLoop@@YAHXZ:
  lea rsp, [rbp+48]
  pop rbp
  ret
$LNend$?inLoop@@YAHXZ:
?inLoop@@YAHXZ ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?inLoop@@YAHXZ DD imagerel $LNbeg$?inLoop@@YAHXZ
  DD imagerel $LNend$?inLoop@@YAHXZ
  DD imagerel $unwind$?inLoop@@YAHXZ
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?inLoop@@YAHXZ DB 01H
  DB $LNprolog$?inLoop@@YAHXZ-$LNbeg$?inLoop@@YAHXZ
  DB 3
  DB 05H
  DB $LNfp$?inLoop@@YAHXZ-$LNbeg$?inLoop@@YAHXZ
  DB 03H
  DB $LNalloc$?inLoop@@YAHXZ-$LNbeg$?inLoop@@YAHXZ
  DB 052H
  DB $LNpush$?inLoop@@YAHXZ-$LNbeg$?inLoop@@YAHXZ
  DB 050H
  DW 0
.xdata ENDS

.CODE
??__Flate@?1??lazy@@YAH_N@Z@YAXXZ PROC
$LNbeg$??__Flate@?1??lazy@@YAH_N@Z@YAXXZ:
  push rbp
$LNpush$??__Flate@?1??lazy@@YAH_N@Z@YAXXZ:
  sub rsp, 32
$LNalloc$??__Flate@?1??lazy@@YAH_N@Z@YAXXZ:
  mov rbp, rsp
$LNfp$??__Flate@?1??lazy@@YAH_N@Z@YAXXZ:
$LNprolog$??__Flate@?1??lazy@@YAH_N@Z@YAXXZ:
  lea rax, [$?lazy@@YAH_N@Z_late]
  push rax
  pop rcx
  mov rax, 0
  call ??1S@@QEAA@XZ
  mov rax, 0
$_L_return_??__Flate@?1??lazy@@YAH_N@Z@YAXXZ:
  lea rsp, [rbp+32]
  pop rbp
  ret
$LNend$??__Flate@?1??lazy@@YAH_N@Z@YAXXZ:
??__Flate@?1??lazy@@YAH_N@Z@YAXXZ ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$??__Flate@?1??lazy@@YAH_N@Z@YAXXZ DD imagerel $LNbeg$??__Flate@?1??lazy@@YAH_N@Z@YAXXZ
  DD imagerel $LNend$??__Flate@?1??lazy@@YAH_N@Z@YAXXZ
  DD imagerel $unwind$??__Flate@?1??lazy@@YAH_N@Z@YAXXZ
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$??__Flate@?1??lazy@@YAH_N@Z@YAXXZ DB 01H
  DB $LNprolog$??__Flate@?1??lazy@@YAH_N@Z@YAXXZ-$LNbeg$??__Flate@?1??lazy@@YAH_N@Z@YAXXZ
  DB 3
  DB 05H
  DB $LNfp$??__Flate@?1??lazy@@YAH_N@Z@YAXXZ-$LNbeg$??__Flate@?1??lazy@@YAH_N@Z@YAXXZ
  DB 03H
  DB $LNalloc$??__Flate@?1??lazy@@YAH_N@Z@YAXXZ-$LNbeg$??__Flate@?1??lazy@@YAH_N@Z@YAXXZ
  DB 032H
  DB $LNpush$??__Flate@?1??lazy@@YAH_N@Z@YAXXZ-$LNbeg$??__Flate@?1??lazy@@YAH_N@Z@YAXXZ
  DB 050H
  DW 0
.xdata ENDS

.CODE
?lazy@@YAH_N@Z PROC
$LNbeg$?lazy@@YAH_N@Z:
  push rbp
$LNpush$?lazy@@YAH_N@Z:
  sub rsp, 48
$LNalloc$?lazy@@YAH_N@Z:
  mov rbp, rsp
$LNfp$?lazy@@YAH_N@Z:
$LNprolog$?lazy@@YAH_N@Z:
  mov rax, rcx
  mov BYTE PTR [rbp+47], al
  lea rax, [rbp+47]
  movzx rax, BYTE PTR [rax]
  cmp rax, 0
  je $_L_?lazy@@YAH_N@Z_end_0
  lea rax, [$?lazy@@YAH_N@Z_late$guard]
  push rax
  pop rcx
  mov rax, 0
  call _Init_thread_header
  mov rax, -1
  push rax
  lea rax, [$?lazy@@YAH_N@Z_late$guard]
  movsxd rax, DWORD PTR [rax]
  pop r10
  cmp eax, r10d
  sete al
  movzx rax, al
  cmp rax, 0
  je $_L_?lazy@@YAH_N@Z_end_1
  lea rax, [$?lazy@@YAH_N@Z_late]
  push rax
  mov rax, 50
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call ??0S@@QEAA@H@Z
  lea rax, [??__Flate@?1??lazy@@YAH_N@Z@YAXXZ]
  push rax
  pop rcx
  mov rax, 0
  call atexit
  movsxd rax, eax
  lea rax, [$?lazy@@YAH_N@Z_late$guard]
  push rax
  pop rcx
  mov rax, 0
  call _Init_thread_footer
$_L_?lazy@@YAH_N@Z_end_1:
  lea rax, [$?lazy@@YAH_N@Z_late]
  movsxd rax, DWORD PTR [rax]
  jmp $_L_return_?lazy@@YAH_N@Z
$_L_?lazy@@YAH_N@Z_end_0:
  mov rax, 1
  neg eax
  movsxd rax, eax
  jmp $_L_return_?lazy@@YAH_N@Z
  mov rax, 0
$_L_return_?lazy@@YAH_N@Z:
  lea rsp, [rbp+48]
  pop rbp
  ret
$LNend$?lazy@@YAH_N@Z:
?lazy@@YAH_N@Z ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?lazy@@YAH_N@Z DD imagerel $LNbeg$?lazy@@YAH_N@Z
  DD imagerel $LNend$?lazy@@YAH_N@Z
  DD imagerel $unwind$?lazy@@YAH_N@Z
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?lazy@@YAH_N@Z DB 01H
  DB $LNprolog$?lazy@@YAH_N@Z-$LNbeg$?lazy@@YAH_N@Z
  DB 3
  DB 05H
  DB $LNfp$?lazy@@YAH_N@Z-$LNbeg$?lazy@@YAH_N@Z
  DB 03H
  DB $LNalloc$?lazy@@YAH_N@Z-$LNbeg$?lazy@@YAH_N@Z
  DB 052H
  DB $LNpush$?lazy@@YAH_N@Z-$LNbeg$?lazy@@YAH_N@Z
  DB 050H
  DW 0
.xdata ENDS

.CODE
main PROC
$LNbeg$main:
  push rbp
$LNpush$main:
  sub rsp, 64
$LNalloc$main:
  mov rbp, rsp
$LNfp$main:
$LNprolog$main:
  mov rax, 0
  call ?lfWatch@@YAXXZ
  lea rax, [rbp+60]
  push rax
  mov rax, 1
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call ??0S@@QEAA@H@Z
  mov QWORD PTR [rbp+32], -2
$_L_main_try_0:
  lea rax, [$_L_str_5]
  push rax
  sub rsp, 8
  mov rax, 3
  push rax
  pop rcx
  mov rax, 0
  sub rsp, 32
  call ?count@@YAHH@Z
  add rsp, 40
  movsxd rax, eax
  push rax
  mov rax, 30
  push rax
  pop rcx
  mov rax, 0
  sub rsp, 32
  call ?count@@YAHH@Z
  add rsp, 32
  movsxd rax, eax
  push rax
  sub rsp, 8
  mov rax, 300
  push rax
  pop rcx
  mov rax, 0
  sub rsp, 32
  call ?count@@YAHH@Z
  add rsp, 40
  movsxd rax, eax
  push rax
  pop r9
  pop r8
  pop rdx
  pop rcx
  mov rax, 0
  call printf
  movsxd rax, eax
  lea rax, [$_L_str_6]
  push rax
  sub rsp, 8
  mov rax, 0
  sub rsp, 32
  call ?inLoop@@YAHXZ
  add rsp, 40
  movsxd rax, eax
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call printf
  movsxd rax, eax
  lea rax, [$_L_str_7]
  push rax
  sub rsp, 8
  mov rax, 0
  push rax
  pop rcx
  mov rax, 0
  sub rsp, 32
  call ?lazy@@YAH_N@Z
  add rsp, 40
  movsxd rax, eax
  push rax
  mov rax, 1
  push rax
  pop rcx
  mov rax, 0
  sub rsp, 32
  call ?lazy@@YAH_N@Z
  add rsp, 32
  movsxd rax, eax
  push rax
  sub rsp, 8
  mov rax, 1
  push rax
  pop rcx
  mov rax, 0
  sub rsp, 32
  call ?lazy@@YAH_N@Z
  add rsp, 40
  movsxd rax, eax
  push rax
  pop r9
  pop r8
  pop rdx
  pop rcx
  mov rax, 0
  call printf
  movsxd rax, eax
  mov rax, 0
  push rax
  lea rax, [rbp+56]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  lea rax, [rbp+60]
  push rax
  pop rcx
  mov rax, 0
  call ??1S@@QEAA@XZ
  lea rax, [rbp+56]
  movsxd rax, DWORD PTR [rax]
  jmp $_L_return_main
  lea rax, [rbp+60]
  push rax
  pop rcx
  mov rax, 0
  call ??1S@@QEAA@XZ
  nop
$_L_main_tryend_0:
$_L_main_caught_0:
  nop
$_L_main_stateend_1:
  mov rax, 0
$_L_return_main:
  lea rsp, [rbp+64]
  pop rbp
  ret
$LNend$main:
main ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$main DD imagerel $LNbeg$main
  DD imagerel $LNend$main
  DD imagerel $unwind$main
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$main DB 019H
  DB $LNprolog$main-$LNbeg$main
  DB 3
  DB 05H
  DB $LNfp$main-$LNbeg$main
  DB 03H
  DB $LNalloc$main-$LNbeg$main
  DB 072H
  DB $LNpush$main-$LNbeg$main
  DB 050H
  DW 0
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$main
.xdata ENDS

.CODE

.text$x SEGMENT ALIGN(16) 'CODE'
main$catch$0 PROC
$LNbeg$main$catch$0:
  mov QWORD PTR [rsp+16], rdx
  push rbp
$LNpush$main$catch$0:
  sub rsp, 32
$LNprolog$main$catch$0:
  mov rbp, rdx
  lea rax, [rbp+60]
  push rax
  pop rcx
  mov rax, 0
  call ??1S@@QEAA@XZ
$LNleave$main$catch$0:
  add rsp, 32
  pop rbp
  ret 0
$LNend$main$catch$0:
main$catch$0 ENDP
.text$x ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$main$catch$0 DB 019H
  DB $LNprolog$main$catch$0-$LNbeg$main$catch$0
  DB 02H
  DB 00H
  DB $LNprolog$main$catch$0-$LNbeg$main$catch$0
  DB 032H
  DB $LNpush$main$catch$0-$LNbeg$main$catch$0
  DB 050H
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$main
.xdata ENDS

.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$cppxdata$main DD 019930522H
  DD 1
  DD imagerel $stateUnwindMap$main
  DD 0
  DD 00H
  DD 3
  DD imagerel $ip2state$main
  DD 32
  DD 00H
  DD 01H
$stateUnwindMap$main DD 0ffffffffH
  DD imagerel main$catch$0
$ip2state$main DD imagerel $LNbeg$main
  DD 0ffffffffH
  DD imagerel $_L_main_try_0
  DD 0
  DD imagerel $_L_main_stateend_1
  DD 0ffffffffH
.xdata ENDS

.CODE

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$main$catch$0 DD imagerel $LNbeg$main$catch$0
  DD imagerel $LNend$main$catch$0
  DD imagerel $unwind$main$catch$0
.pdata ENDS

END
