; Generated by cxx1 for x86_64-windows, in MASM syntax for ml64.
; The instruction selection is the same one the Linux backend makes;
; only the spelling is Microsoft's. See src/backend/Masm.cpp.

OPTION DOTNAME
OPTION NOSCOPED
OPTION PROC:PRIVATE

PUBLIC ??0Oops@@QEAA@H@Z
PUBLIC ??0Shape@@QEAA@XZ
PUBLIC ??0Square@@QEAA@H@Z
PUBLIC ??1Shape@@UEAA@XZ
PUBLIC ??1Square@@UEAA@XZ
PUBLIC ??_7Shape@@6B@
PUBLIC ??_7Square@@6B@
PUBLIC ??_GShape@@UEAAPEAXI@Z
PUBLIC ??_GSquare@@UEAAPEAXI@Z
PUBLIC ??_R0?AUOops@@@8
PUBLIC ??_R0?AUShape@@@8
PUBLIC ??_R0?AUSquare@@@8
PUBLIC ??_R1A@?0A@EA@Shape@@8
PUBLIC ??_R1A@?0A@EA@Square@@8
PUBLIC ??_R2Shape@@8
PUBLIC ??_R2Square@@8
PUBLIC ??_R3Shape@@8
PUBLIC ??_R3Square@@8
PUBLIC ??_R4Shape@@6B@
PUBLIC ??_R4Square@@6B@
PUBLIC ?area@Shape@@UEBAHXZ
PUBLIC ?area@Square@@UEBAHXZ
PUBLIC ?fromB@@YAHH@Z
PUBLIC ?hits@?$Counter@H@@2HA
PUBLIC ?twice@@YAHH@Z
PUBLIC _CT??_R0?AUOops@@@84
PUBLIC _CTA1?AUOops@@
PUBLIC _TI1?AUOops@@
EXTERN ??3@YAXPEAX@Z:PROC
EXTERN _CxxThrowException:PROC
EXTERN __CxxFrameHandler3:PROC
EXTERN printf:PROC


EXTRN ??_7type_info@@6B@:QWORD
.data$r SEGMENT ALIGN(16) 'DATA' COMDAT(??_R0?AUShape@@@8)
??_R0?AUShape@@@8 DQ ??_7type_info@@6B@
  DQ 0
  DB '.?AUShape@@', 00H
.data$r ENDS
.rdata$r SEGMENT READONLY ALIGN(4) 'DATA' COMDAT(??_R1A@?0A@EA@Shape@@8)
??_R1A@?0A@EA@Shape@@8 DD imagerel ??_R0?AUShape@@@8
  DD 00H
  DD 00H
  DD 0ffffffffH
  DD 00H
  DD 040H
  DD imagerel ??_R3Shape@@8
.rdata$r ENDS
.rdata$r SEGMENT READONLY ALIGN(4) 'DATA' COMDAT(??_R2Shape@@8)
??_R2Shape@@8 DD imagerel ??_R1A@?0A@EA@Shape@@8
  DD 00H
.rdata$r ENDS
.rdata$r SEGMENT READONLY ALIGN(4) 'DATA' COMDAT(??_R3Shape@@8)
??_R3Shape@@8 DD 00H
  DD 00H
  DD 01H
  DD imagerel ??_R2Shape@@8
.rdata$r ENDS
.rdata$r SEGMENT READONLY ALIGN(4) 'DATA' COMDAT(??_R4Shape@@6B@)
??_R4Shape@@6B@ DD 01H
  DD 00H
  DD 00H
  DD imagerel ??_R0?AUShape@@@8
  DD imagerel ??_R3Shape@@8
  DD imagerel ??_R4Shape@@6B@
.rdata$r ENDS
.data$r SEGMENT ALIGN(16) 'DATA' COMDAT(??_R0?AUSquare@@@8)
??_R0?AUSquare@@@8 DQ ??_7type_info@@6B@
  DQ 0
  DB '.?AUSquare@@', 00H
.data$r ENDS
.rdata$r SEGMENT READONLY ALIGN(4) 'DATA' COMDAT(??_R1A@?0A@EA@Square@@8)
??_R1A@?0A@EA@Square@@8 DD imagerel ??_R0?AUSquare@@@8
  DD 01H
  DD 00H
  DD 0ffffffffH
  DD 00H
  DD 040H
  DD imagerel ??_R3Square@@8
.rdata$r ENDS
.rdata$r SEGMENT READONLY ALIGN(4) 'DATA' COMDAT(??_R2Square@@8)
??_R2Square@@8 DD imagerel ??_R1A@?0A@EA@Square@@8
  DD imagerel ??_R1A@?0A@EA@Shape@@8
  DD 00H
.rdata$r ENDS
.rdata$r SEGMENT READONLY ALIGN(4) 'DATA' COMDAT(??_R3Square@@8)
??_R3Square@@8 DD 00H
  DD 00H
  DD 02H
  DD imagerel ??_R2Square@@8
.rdata$r ENDS
.rdata$r SEGMENT READONLY ALIGN(4) 'DATA' COMDAT(??_R4Square@@6B@)
??_R4Square@@6B@ DD 01H
  DD 00H
  DD 00H
  DD imagerel ??_R0?AUSquare@@@8
  DD imagerel ??_R3Square@@8
  DD imagerel ??_R4Square@@6B@
.rdata$r ENDS
.data$r SEGMENT ALIGN(16) 'DATA' COMDAT(??_R0?AUOops@@@8)
??_R0?AUOops@@@8 DQ ??_7type_info@@6B@
  DQ 0
  DB '.?AUOops@@', 00H
.data$r ENDS
.xdata$x SEGMENT READONLY ALIGN(8) 'DATA' COMDAT(_CT??_R0?AUOops@@@84)
_CT??_R0?AUOops@@@84 DD 00H
  DD imagerel ??_R0?AUOops@@@8
  DD 0
  DD 0ffffffffH
  DD 00H
  DD 4
  DD 00H
.xdata$x ENDS
.xdata$x SEGMENT READONLY ALIGN(4) 'DATA' COMDAT(_CTA1?AUOops@@)
_CTA1?AUOops@@ DD 1
  DD imagerel _CT??_R0?AUOops@@@84
.xdata$x ENDS
.xdata$x SEGMENT READONLY ALIGN(4) 'DATA' COMDAT(_TI1?AUOops@@)
_TI1?AUOops@@ DD 00H
  DD 00H
  DD 00H
  DD imagerel _CTA1?AUOops@@
.xdata$x ENDS

.CONST
$_L_str_0 DB 98, 58, 32, 99, 97, 117, 103, 104, 116, 32, 37, 100, 10, 0

CONST SEGMENT READONLY ALIGN(16) 'DATA' COMDAT(??_7Shape@@6B@)
  ALIGN 16
  DQ ??_R4Shape@@6B@
??_7Shape@@6B@ DQ ??_GShape@@UEAAPEAXI@Z
  DQ ?area@Shape@@UEBAHXZ
CONST ENDS

CONST SEGMENT READONLY ALIGN(16) 'DATA' COMDAT(??_7Square@@6B@)
  ALIGN 16
  DQ ??_R4Square@@6B@
??_7Square@@6B@ DQ ??_GSquare@@UEAAPEAXI@Z
  DQ ?area@Square@@UEBAHXZ
CONST ENDS

.DATA?

_BSS SEGMENT ALIGN(16) 'BSS' COMDAT(?hits@?$Counter@H@@2HA)
  ALIGN 4
?hits@?$Counter@H@@2HA DB 4 DUP (?)
_BSS ENDS

.CODE
.text$mn SEGMENT ALIGN(16) 'CODE' COMDAT(?twice@@YAHH@Z)
?twice@@YAHH@Z PROC
$LNbeg$?twice@@YAHH@Z:
  push rbp
$LNpush$?twice@@YAHH@Z:
  sub rsp, 16
$LNalloc$?twice@@YAHH@Z:
  mov rbp, rsp
$LNfp$?twice@@YAHH@Z:
$LNprolog$?twice@@YAHH@Z:
  mov rax, rcx
  mov DWORD PTR [rbp+12], eax
  mov rax, 2
  push rax
  lea rax, [rbp+12]
  movsxd rax, DWORD PTR [rax]
  pop r10
  imul eax, r10d
  movsxd rax, eax
  jmp $_L_return_?twice@@YAHH@Z
  mov rax, 0
$_L_return_?twice@@YAHH@Z:
  lea rsp, [rbp+16]
  pop rbp
  ret
$LNend$?twice@@YAHH@Z:
?twice@@YAHH@Z ENDP
.text$mn ENDS

.pdata SEGMENT READONLY ALIGN(4) 'DATA' ASSOCIATIVE(?twice@@YAHH@Z)
$pdata$?twice@@YAHH@Z DD imagerel $LNbeg$?twice@@YAHH@Z
  DD imagerel $LNend$?twice@@YAHH@Z
  DD imagerel $unwind$?twice@@YAHH@Z
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA' ASSOCIATIVE(?twice@@YAHH@Z)
$unwind$?twice@@YAHH@Z DB 01H
  DB $LNprolog$?twice@@YAHH@Z-$LNbeg$?twice@@YAHH@Z
  DB 3
  DB 05H
  DB $LNfp$?twice@@YAHH@Z-$LNbeg$?twice@@YAHH@Z
  DB 03H
  DB $LNalloc$?twice@@YAHH@Z-$LNbeg$?twice@@YAHH@Z
  DB 012H
  DB $LNpush$?twice@@YAHH@Z-$LNbeg$?twice@@YAHH@Z
  DB 050H
  DW 0
.xdata ENDS

.CODE
.text$mn SEGMENT ALIGN(16) 'CODE' COMDAT(??1Shape@@UEAA@XZ)
??1Shape@@UEAA@XZ PROC
$LNbeg$??1Shape@@UEAA@XZ:
  push rbp
$LNpush$??1Shape@@UEAA@XZ:
  sub rsp, 16
$LNalloc$??1Shape@@UEAA@XZ:
  mov rbp, rsp
$LNfp$??1Shape@@UEAA@XZ:
$LNprolog$??1Shape@@UEAA@XZ:
  mov rax, rcx
  mov QWORD PTR [rbp+8], rax
  lea rax, [??_7Shape@@6B@]
  push rax
  lea rax, [rbp+8]
  mov rax, QWORD PTR [rax]
  mov r10, rax
  pop rax
  mov QWORD PTR [r10], rax
  mov rax, 0
$_L_return_??1Shape@@UEAA@XZ:
  lea rsp, [rbp+16]
  pop rbp
  ret
$LNend$??1Shape@@UEAA@XZ:
??1Shape@@UEAA@XZ ENDP
.text$mn ENDS

.pdata SEGMENT READONLY ALIGN(4) 'DATA' ASSOCIATIVE(??1Shape@@UEAA@XZ)
$pdata$??1Shape@@UEAA@XZ DD imagerel $LNbeg$??1Shape@@UEAA@XZ
  DD imagerel $LNend$??1Shape@@UEAA@XZ
  DD imagerel $unwind$??1Shape@@UEAA@XZ
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA' ASSOCIATIVE(??1Shape@@UEAA@XZ)
$unwind$??1Shape@@UEAA@XZ DB 01H
  DB $LNprolog$??1Shape@@UEAA@XZ-$LNbeg$??1Shape@@UEAA@XZ
  DB 3
  DB 05H
  DB $LNfp$??1Shape@@UEAA@XZ-$LNbeg$??1Shape@@UEAA@XZ
  DB 03H
  DB $LNalloc$??1Shape@@UEAA@XZ-$LNbeg$??1Shape@@UEAA@XZ
  DB 012H
  DB $LNpush$??1Shape@@UEAA@XZ-$LNbeg$??1Shape@@UEAA@XZ
  DB 050H
  DW 0
.xdata ENDS

.CODE
.text$mn SEGMENT ALIGN(16) 'CODE' COMDAT(??_GShape@@UEAAPEAXI@Z)
??_GShape@@UEAAPEAXI@Z PROC
$LNbeg$??_GShape@@UEAAPEAXI@Z:
  push rbp
$LNpush$??_GShape@@UEAAPEAXI@Z:
  sub rsp, 48
$LNalloc$??_GShape@@UEAAPEAXI@Z:
  mov rbp, rsp
$LNfp$??_GShape@@UEAAPEAXI@Z:
$LNprolog$??_GShape@@UEAAPEAXI@Z:
  mov rax, rcx
  mov QWORD PTR [rbp+40], rax
  mov rax, rdx
  mov DWORD PTR [rbp+36], eax
  lea rax, [rbp+40]
  mov rax, QWORD PTR [rax]
  push rax
  pop rcx
  mov rax, 0
  call ??1Shape@@UEAA@XZ
  mov rax, 1
  push rax
  lea rax, [rbp+36]
  mov eax, DWORD PTR [rax]
  pop r10
  and eax, r10d
  mov eax, eax
  cmp rax, 0
  je $_L_??_GShape@@UEAAPEAXI@Z_end_0
  lea rax, [rbp+40]
  mov rax, QWORD PTR [rax]
  push rax
  pop rcx
  mov rax, 0
  call ??3@YAXPEAX@Z
$_L_??_GShape@@UEAAPEAXI@Z_end_0:
  lea rax, [rbp+40]
  mov rax, QWORD PTR [rax]
  jmp $_L_return_??_GShape@@UEAAPEAXI@Z
  mov rax, 0
$_L_return_??_GShape@@UEAAPEAXI@Z:
  lea rsp, [rbp+48]
  pop rbp
  ret
$LNend$??_GShape@@UEAAPEAXI@Z:
??_GShape@@UEAAPEAXI@Z ENDP
.text$mn ENDS

.pdata SEGMENT READONLY ALIGN(4) 'DATA' ASSOCIATIVE(??_GShape@@UEAAPEAXI@Z)
$pdata$??_GShape@@UEAAPEAXI@Z DD imagerel $LNbeg$??_GShape@@UEAAPEAXI@Z
  DD imagerel $LNend$??_GShape@@UEAAPEAXI@Z
  DD imagerel $unwind$??_GShape@@UEAAPEAXI@Z
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA' ASSOCIATIVE(??_GShape@@UEAAPEAXI@Z)
$unwind$??_GShape@@UEAAPEAXI@Z DB 01H
  DB $LNprolog$??_GShape@@UEAAPEAXI@Z-$LNbeg$??_GShape@@UEAAPEAXI@Z
  DB 3
  DB 05H
  DB $LNfp$??_GShape@@UEAAPEAXI@Z-$LNbeg$??_GShape@@UEAAPEAXI@Z
  DB 03H
  DB $LNalloc$??_GShape@@UEAAPEAXI@Z-$LNbeg$??_GShape@@UEAAPEAXI@Z
  DB 052H
  DB $LNpush$??_GShape@@UEAAPEAXI@Z-$LNbeg$??_GShape@@UEAAPEAXI@Z
  DB 050H
  DW 0
.xdata ENDS

.CODE
.text$mn SEGMENT ALIGN(16) 'CODE' COMDAT(?area@Shape@@UEBAHXZ)
?area@Shape@@UEBAHXZ PROC
$LNbeg$?area@Shape@@UEBAHXZ:
  push rbp
$LNpush$?area@Shape@@UEBAHXZ:
  sub rsp, 16
$LNalloc$?area@Shape@@UEBAHXZ:
  mov rbp, rsp
$LNfp$?area@Shape@@UEBAHXZ:
$LNprolog$?area@Shape@@UEBAHXZ:
  mov rax, rcx
  mov QWORD PTR [rbp+8], rax
  mov rax, 1
  jmp $_L_return_?area@Shape@@UEBAHXZ
  mov rax, 0
$_L_return_?area@Shape@@UEBAHXZ:
  lea rsp, [rbp+16]
  pop rbp
  ret
$LNend$?area@Shape@@UEBAHXZ:
?area@Shape@@UEBAHXZ ENDP
.text$mn ENDS

.pdata SEGMENT READONLY ALIGN(4) 'DATA' ASSOCIATIVE(?area@Shape@@UEBAHXZ)
$pdata$?area@Shape@@UEBAHXZ DD imagerel $LNbeg$?area@Shape@@UEBAHXZ
  DD imagerel $LNend$?area@Shape@@UEBAHXZ
  DD imagerel $unwind$?area@Shape@@UEBAHXZ
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA' ASSOCIATIVE(?area@Shape@@UEBAHXZ)
$unwind$?area@Shape@@UEBAHXZ DB 01H
  DB $LNprolog$?area@Shape@@UEBAHXZ-$LNbeg$?area@Shape@@UEBAHXZ
  DB 3
  DB 05H
  DB $LNfp$?area@Shape@@UEBAHXZ-$LNbeg$?area@Shape@@UEBAHXZ
  DB 03H
  DB $LNalloc$?area@Shape@@UEBAHXZ-$LNbeg$?area@Shape@@UEBAHXZ
  DB 012H
  DB $LNpush$?area@Shape@@UEBAHXZ-$LNbeg$?area@Shape@@UEBAHXZ
  DB 050H
  DW 0
.xdata ENDS

.CODE
.text$mn SEGMENT ALIGN(16) 'CODE' COMDAT(??0Square@@QEAA@H@Z)
??0Square@@QEAA@H@Z PROC
$LNbeg$??0Square@@QEAA@H@Z:
  push rbp
$LNpush$??0Square@@QEAA@H@Z:
  sub rsp, 48
$LNalloc$??0Square@@QEAA@H@Z:
  mov rbp, rsp
$LNfp$??0Square@@QEAA@H@Z:
$LNprolog$??0Square@@QEAA@H@Z:
  mov rax, rcx
  mov QWORD PTR [rbp+32], rax
  mov rax, rdx
  mov DWORD PTR [rbp+44], eax
  lea rax, [rbp+32]
  mov rax, QWORD PTR [rax]
  push rax
  pop rcx
  mov rax, 0
  call ??0Shape@@QEAA@XZ
  lea rax, [??_7Square@@6B@]
  push rax
  lea rax, [rbp+32]
  mov rax, QWORD PTR [rax]
  mov r10, rax
  pop rax
  mov QWORD PTR [r10], rax
  lea rax, [rbp+44]
  movsxd rax, DWORD PTR [rax]
  push rax
  lea rax, [rbp+32]
  mov rax, QWORD PTR [rax]
  add rax, 8
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  mov rax, 0
$_L_return_??0Square@@QEAA@H@Z:
  mov rax, [rbp+32]
  lea rsp, [rbp+48]
  pop rbp
  ret
$LNend$??0Square@@QEAA@H@Z:
??0Square@@QEAA@H@Z ENDP
.text$mn ENDS

.pdata SEGMENT READONLY ALIGN(4) 'DATA' ASSOCIATIVE(??0Square@@QEAA@H@Z)
$pdata$??0Square@@QEAA@H@Z DD imagerel $LNbeg$??0Square@@QEAA@H@Z
  DD imagerel $LNend$??0Square@@QEAA@H@Z
  DD imagerel $unwind$??0Square@@QEAA@H@Z
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA' ASSOCIATIVE(??0Square@@QEAA@H@Z)
$unwind$??0Square@@QEAA@H@Z DB 01H
  DB $LNprolog$??0Square@@QEAA@H@Z-$LNbeg$??0Square@@QEAA@H@Z
  DB 3
  DB 05H
  DB $LNfp$??0Square@@QEAA@H@Z-$LNbeg$??0Square@@QEAA@H@Z
  DB 03H
  DB $LNalloc$??0Square@@QEAA@H@Z-$LNbeg$??0Square@@QEAA@H@Z
  DB 052H
  DB $LNpush$??0Square@@QEAA@H@Z-$LNbeg$??0Square@@QEAA@H@Z
  DB 050H
  DW 0
.xdata ENDS

.CODE
.text$mn SEGMENT ALIGN(16) 'CODE' COMDAT(?area@Square@@UEBAHXZ)
?area@Square@@UEBAHXZ PROC
$LNbeg$?area@Square@@UEBAHXZ:
  push rbp
$LNpush$?area@Square@@UEBAHXZ:
  sub rsp, 16
$LNalloc$?area@Square@@UEBAHXZ:
  mov rbp, rsp
$LNfp$?area@Square@@UEBAHXZ:
$LNprolog$?area@Square@@UEBAHXZ:
  mov rax, rcx
  mov QWORD PTR [rbp+8], rax
  lea rax, [rbp+8]
  mov rax, QWORD PTR [rax]
  add rax, 8
  movsxd rax, DWORD PTR [rax]
  push rax
  lea rax, [rbp+8]
  mov rax, QWORD PTR [rax]
  add rax, 8
  movsxd rax, DWORD PTR [rax]
  pop r10
  imul eax, r10d
  movsxd rax, eax
  movsxd rax, eax
  jmp $_L_return_?area@Square@@UEBAHXZ
  mov rax, 0
$_L_return_?area@Square@@UEBAHXZ:
  lea rsp, [rbp+16]
  pop rbp
  ret
$LNend$?area@Square@@UEBAHXZ:
?area@Square@@UEBAHXZ ENDP
.text$mn ENDS

.pdata SEGMENT READONLY ALIGN(4) 'DATA' ASSOCIATIVE(?area@Square@@UEBAHXZ)
$pdata$?area@Square@@UEBAHXZ DD imagerel $LNbeg$?area@Square@@UEBAHXZ
  DD imagerel $LNend$?area@Square@@UEBAHXZ
  DD imagerel $unwind$?area@Square@@UEBAHXZ
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA' ASSOCIATIVE(?area@Square@@UEBAHXZ)
$unwind$?area@Square@@UEBAHXZ DB 01H
  DB $LNprolog$?area@Square@@UEBAHXZ-$LNbeg$?area@Square@@UEBAHXZ
  DB 3
  DB 05H
  DB $LNfp$?area@Square@@UEBAHXZ-$LNbeg$?area@Square@@UEBAHXZ
  DB 03H
  DB $LNalloc$?area@Square@@UEBAHXZ-$LNbeg$?area@Square@@UEBAHXZ
  DB 012H
  DB $LNpush$?area@Square@@UEBAHXZ-$LNbeg$?area@Square@@UEBAHXZ
  DB 050H
  DW 0
.xdata ENDS

.CODE
.text$mn SEGMENT ALIGN(16) 'CODE' COMDAT(??0Oops@@QEAA@H@Z)
??0Oops@@QEAA@H@Z PROC
$LNbeg$??0Oops@@QEAA@H@Z:
  push rbp
$LNpush$??0Oops@@QEAA@H@Z:
  sub rsp, 16
$LNalloc$??0Oops@@QEAA@H@Z:
  mov rbp, rsp
$LNfp$??0Oops@@QEAA@H@Z:
$LNprolog$??0Oops@@QEAA@H@Z:
  mov rax, rcx
  mov QWORD PTR [rbp], rax
  mov rax, rdx
  mov DWORD PTR [rbp+12], eax
  lea rax, [rbp+12]
  movsxd rax, DWORD PTR [rax]
  push rax
  lea rax, [rbp]
  mov rax, QWORD PTR [rax]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  mov rax, 0
$_L_return_??0Oops@@QEAA@H@Z:
  mov rax, [rbp]
  lea rsp, [rbp+16]
  pop rbp
  ret
$LNend$??0Oops@@QEAA@H@Z:
??0Oops@@QEAA@H@Z ENDP
.text$mn ENDS

.pdata SEGMENT READONLY ALIGN(4) 'DATA' ASSOCIATIVE(??0Oops@@QEAA@H@Z)
$pdata$??0Oops@@QEAA@H@Z DD imagerel $LNbeg$??0Oops@@QEAA@H@Z
  DD imagerel $LNend$??0Oops@@QEAA@H@Z
  DD imagerel $unwind$??0Oops@@QEAA@H@Z
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA' ASSOCIATIVE(??0Oops@@QEAA@H@Z)
$unwind$??0Oops@@QEAA@H@Z DB 01H
  DB $LNprolog$??0Oops@@QEAA@H@Z-$LNbeg$??0Oops@@QEAA@H@Z
  DB 3
  DB 05H
  DB $LNfp$??0Oops@@QEAA@H@Z-$LNbeg$??0Oops@@QEAA@H@Z
  DB 03H
  DB $LNalloc$??0Oops@@QEAA@H@Z-$LNbeg$??0Oops@@QEAA@H@Z
  DB 012H
  DB $LNpush$??0Oops@@QEAA@H@Z-$LNbeg$??0Oops@@QEAA@H@Z
  DB 050H
  DW 0
.xdata ENDS

.CODE
?fromB@@YAHH@Z PROC
$LNbeg$?fromB@@YAHH@Z:
  push rbp
$LNpush$?fromB@@YAHH@Z:
  sub rsp, 160
$LNalloc$?fromB@@YAHH@Z:
  mov rbp, rsp
$LNfp$?fromB@@YAHH@Z:
$LNprolog$?fromB@@YAHH@Z:
  mov rax, rcx
  mov DWORD PTR [rbp+156], eax
  lea rax, [?hits@?$Counter@H@@2HA]
  push rax
  movsxd rax, DWORD PTR [rax]
  push rax
  add rax, 1
  pop rdx
  pop r10
  mov DWORD PTR [r10], eax
  mov rax, rdx
  lea rax, [rbp+128]
  push rax
  lea rax, [rbp+156]
  movsxd rax, DWORD PTR [rax]
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call ??0Square@@QEAA@H@Z
  mov QWORD PTR [rbp+32], -2
$_L_?fromB@@YAHH@Z_try_0:
  lea rax, [rbp+128]
  push rax
  lea rax, [rbp+120]
  mov r10, rax
  pop rax
  mov QWORD PTR [r10], rax
  lea rax, [rbp+120]
  mov rax, QWORD PTR [rax]
  push rax
  lea rax, [rbp+112]
  mov r10, rax
  pop rax
  mov QWORD PTR [r10], rax
  mov rax, 8
  push rax
  lea rax, [rbp+112]
  mov rax, QWORD PTR [rax]
  mov rax, QWORD PTR [rax]
  pop r10
  add rax, r10
  mov rax, QWORD PTR [rax]
  push rax
  lea rax, [rbp+112]
  mov rax, QWORD PTR [rax]
  push rax
  pop rcx
  pop r11
  mov rax, 0
  call r11
  movsxd rax, eax
  push rax
  pop rcx
  mov rax, 0
  call ?twice@@YAHH@Z
  movsxd rax, eax
  push rax
  lea rax, [rbp+108]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  mov QWORD PTR [rbp+32], -2
$_L_?fromB@@YAHH@Z_try_1:
  lea rax, [rbp+88]
  push rax
  lea rax, [rbp+108]
  movsxd rax, DWORD PTR [rax]
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call ??0Oops@@QEAA@H@Z
  lea rax, [rbp+88]
  push rax
  lea rax, [rbp+84]
  mov r10, rax
  pop rax
  mov ecx, DWORD PTR [rax]
  mov DWORD PTR [r10], ecx
  mov rax, r10
  lea rax, [rbp+84]
  push rax
  lea rax, [_TI1?AUOops@@]
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call _CxxThrowException
  nop
$_L_?fromB@@YAHH@Z_tryend_1:
$_L_?fromB@@YAHH@Z_caught_1:
  lea rax, [rbp+108]
  movsxd rax, DWORD PTR [rax]
  push rax
  lea rax, [rbp+60]
  mov r10, rax
  pop rax
  mov DWORD PTR [r10], eax
  movsxd rax, eax
  lea rax, [rbp+128]
  push rax
  pop rcx
  mov rax, 0
  call ??1Square@@UEAA@XZ
  lea rax, [rbp+60]
  movsxd rax, DWORD PTR [rax]
  jmp $_L_return_?fromB@@YAHH@Z
  lea rax, [rbp+128]
  push rax
  pop rcx
  mov rax, 0
  call ??1Square@@UEAA@XZ
  nop
$_L_?fromB@@YAHH@Z_tryend_0:
$_L_?fromB@@YAHH@Z_caught_0:
  nop
$_L_?fromB@@YAHH@Z_stateend_2:
  mov rax, 0
$_L_return_?fromB@@YAHH@Z:
  lea rsp, [rbp+160]
  pop rbp
  ret
$LNend$?fromB@@YAHH@Z:
?fromB@@YAHH@Z ENDP

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?fromB@@YAHH@Z DD imagerel $LNbeg$?fromB@@YAHH@Z
  DD imagerel $LNend$?fromB@@YAHH@Z
  DD imagerel $unwind$?fromB@@YAHH@Z
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?fromB@@YAHH@Z DB 019H
  DB $LNprolog$?fromB@@YAHH@Z-$LNbeg$?fromB@@YAHH@Z
  DB 4
  DB 05H
  DB $LNfp$?fromB@@YAHH@Z-$LNbeg$?fromB@@YAHH@Z
  DB 03H
  DB $LNalloc$?fromB@@YAHH@Z-$LNbeg$?fromB@@YAHH@Z
  DB 01H
  DW 20
  DB $LNpush$?fromB@@YAHH@Z-$LNbeg$?fromB@@YAHH@Z
  DB 050H
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?fromB@@YAHH@Z
.xdata ENDS

.CODE

.text$x SEGMENT ALIGN(16) 'CODE'
?fromB@@YAHH@Z$catch$0 PROC
$LNbeg$?fromB@@YAHH@Z$catch$0:
  mov QWORD PTR [rsp+16], rdx
  push rbp
$LNpush$?fromB@@YAHH@Z$catch$0:
  sub rsp, 32
$LNprolog$?fromB@@YAHH@Z$catch$0:
  mov rbp, rdx
  lea rax, [$_L_str_0]
  push rax
  lea rax, [rbp+72]
  mov rax, QWORD PTR [rax]
  movsxd rax, DWORD PTR [rax]
  push rax
  pop rdx
  pop rcx
  mov rax, 0
  call printf
  movsxd rax, eax
  lea rax, $_L_?fromB@@YAHH@Z_caught_1
$LNleave$?fromB@@YAHH@Z$catch$0:
  add rsp, 32
  pop rbp
  ret 0
$LNend$?fromB@@YAHH@Z$catch$0:
?fromB@@YAHH@Z$catch$0 ENDP
.text$x ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?fromB@@YAHH@Z$catch$0 DB 019H
  DB $LNprolog$?fromB@@YAHH@Z$catch$0-$LNbeg$?fromB@@YAHH@Z$catch$0
  DB 02H
  DB 00H
  DB $LNprolog$?fromB@@YAHH@Z$catch$0-$LNbeg$?fromB@@YAHH@Z$catch$0
  DB 032H
  DB $LNpush$?fromB@@YAHH@Z$catch$0-$LNbeg$?fromB@@YAHH@Z$catch$0
  DB 050H
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?fromB@@YAHH@Z
.xdata ENDS

.text$x SEGMENT ALIGN(16) 'CODE'
?fromB@@YAHH@Z$catch$1 PROC
$LNbeg$?fromB@@YAHH@Z$catch$1:
  mov QWORD PTR [rsp+16], rdx
  push rbp
$LNpush$?fromB@@YAHH@Z$catch$1:
  sub rsp, 32
$LNprolog$?fromB@@YAHH@Z$catch$1:
  mov rbp, rdx
  lea rax, [rbp+128]
  push rax
  pop rcx
  mov rax, 0
  call ??1Square@@UEAA@XZ
$LNleave$?fromB@@YAHH@Z$catch$1:
  add rsp, 32
  pop rbp
  ret 0
$LNend$?fromB@@YAHH@Z$catch$1:
?fromB@@YAHH@Z$catch$1 ENDP
.text$x ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$unwind$?fromB@@YAHH@Z$catch$1 DB 019H
  DB $LNprolog$?fromB@@YAHH@Z$catch$1-$LNbeg$?fromB@@YAHH@Z$catch$1
  DB 02H
  DB 00H
  DB $LNprolog$?fromB@@YAHH@Z$catch$1-$LNbeg$?fromB@@YAHH@Z$catch$1
  DB 032H
  DB $LNpush$?fromB@@YAHH@Z$catch$1-$LNbeg$?fromB@@YAHH@Z$catch$1
  DB 050H
  DD imagerel __CxxFrameHandler3
  DD imagerel $cppxdata$?fromB@@YAHH@Z
.xdata ENDS

.xdata SEGMENT READONLY ALIGN(8) 'DATA'
$cppxdata$?fromB@@YAHH@Z DD 019930522H
  DD 3
  DD imagerel $stateUnwindMap$?fromB@@YAHH@Z
  DD 1
  DD imagerel $tryMap$?fromB@@YAHH@Z
  DD 6
  DD imagerel $ip2state$?fromB@@YAHH@Z
  DD 32
  DD 00H
  DD 01H
$stateUnwindMap$?fromB@@YAHH@Z DD 0ffffffffH
  DD imagerel ?fromB@@YAHH@Z$catch$1
  DD 0
  DD 00H
  DD 0
  DD 00H
$tryMap$?fromB@@YAHH@Z DD 1
  DD 1
  DD 2
  DD 1
  DD imagerel $handlerMap$0$?fromB@@YAHH@Z
$handlerMap$0$?fromB@@YAHH@Z DD 8
  DD imagerel ??_R0?AUOops@@@8
  DD 72
  DD imagerel ?fromB@@YAHH@Z$catch$0
  DD 56
$ip2state$?fromB@@YAHH@Z DD imagerel $LNbeg$?fromB@@YAHH@Z
  DD 0ffffffffH
  DD imagerel $_L_?fromB@@YAHH@Z_try_0
  DD 0
  DD imagerel $_L_?fromB@@YAHH@Z_try_1
  DD 1
  DD imagerel $_L_?fromB@@YAHH@Z_tryend_1
  DD 0
  DD imagerel $_L_?fromB@@YAHH@Z_stateend_2
  DD 0ffffffffH
  DD imagerel ?fromB@@YAHH@Z$catch$0
  DD 2
.xdata ENDS

.CODE
.text$mn SEGMENT ALIGN(16) 'CODE' COMDAT(??0Shape@@QEAA@XZ)
??0Shape@@QEAA@XZ PROC
$LNbeg$??0Shape@@QEAA@XZ:
  push rbp
$LNpush$??0Shape@@QEAA@XZ:
  sub rsp, 16
$LNalloc$??0Shape@@QEAA@XZ:
  mov rbp, rsp
$LNfp$??0Shape@@QEAA@XZ:
$LNprolog$??0Shape@@QEAA@XZ:
  mov rax, rcx
  mov QWORD PTR [rbp+8], rax
  lea rax, [??_7Shape@@6B@]
  push rax
  lea rax, [rbp+8]
  mov rax, QWORD PTR [rax]
  mov r10, rax
  pop rax
  mov QWORD PTR [r10], rax
  mov rax, 0
$_L_return_??0Shape@@QEAA@XZ:
  lea rsp, [rbp+16]
  pop rbp
  ret
$LNend$??0Shape@@QEAA@XZ:
??0Shape@@QEAA@XZ ENDP
.text$mn ENDS

.pdata SEGMENT READONLY ALIGN(4) 'DATA' ASSOCIATIVE(??0Shape@@QEAA@XZ)
$pdata$??0Shape@@QEAA@XZ DD imagerel $LNbeg$??0Shape@@QEAA@XZ
  DD imagerel $LNend$??0Shape@@QEAA@XZ
  DD imagerel $unwind$??0Shape@@QEAA@XZ
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA' ASSOCIATIVE(??0Shape@@QEAA@XZ)
$unwind$??0Shape@@QEAA@XZ DB 01H
  DB $LNprolog$??0Shape@@QEAA@XZ-$LNbeg$??0Shape@@QEAA@XZ
  DB 3
  DB 05H
  DB $LNfp$??0Shape@@QEAA@XZ-$LNbeg$??0Shape@@QEAA@XZ
  DB 03H
  DB $LNalloc$??0Shape@@QEAA@XZ-$LNbeg$??0Shape@@QEAA@XZ
  DB 012H
  DB $LNpush$??0Shape@@QEAA@XZ-$LNbeg$??0Shape@@QEAA@XZ
  DB 050H
  DW 0
.xdata ENDS

.CODE
.text$mn SEGMENT ALIGN(16) 'CODE' COMDAT(??1Square@@UEAA@XZ)
??1Square@@UEAA@XZ PROC
$LNbeg$??1Square@@UEAA@XZ:
  push rbp
$LNpush$??1Square@@UEAA@XZ:
  sub rsp, 48
$LNalloc$??1Square@@UEAA@XZ:
  mov rbp, rsp
$LNfp$??1Square@@UEAA@XZ:
$LNprolog$??1Square@@UEAA@XZ:
  mov rax, rcx
  mov QWORD PTR [rbp+40], rax
  lea rax, [rbp+40]
  mov rax, QWORD PTR [rax]
  push rax
  pop rcx
  mov rax, 0
  call ??1Shape@@UEAA@XZ
  mov rax, 0
$_L_return_??1Square@@UEAA@XZ:
  lea rsp, [rbp+48]
  pop rbp
  ret
$LNend$??1Square@@UEAA@XZ:
??1Square@@UEAA@XZ ENDP
.text$mn ENDS

.pdata SEGMENT READONLY ALIGN(4) 'DATA' ASSOCIATIVE(??1Square@@UEAA@XZ)
$pdata$??1Square@@UEAA@XZ DD imagerel $LNbeg$??1Square@@UEAA@XZ
  DD imagerel $LNend$??1Square@@UEAA@XZ
  DD imagerel $unwind$??1Square@@UEAA@XZ
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA' ASSOCIATIVE(??1Square@@UEAA@XZ)
$unwind$??1Square@@UEAA@XZ DB 01H
  DB $LNprolog$??1Square@@UEAA@XZ-$LNbeg$??1Square@@UEAA@XZ
  DB 3
  DB 05H
  DB $LNfp$??1Square@@UEAA@XZ-$LNbeg$??1Square@@UEAA@XZ
  DB 03H
  DB $LNalloc$??1Square@@UEAA@XZ-$LNbeg$??1Square@@UEAA@XZ
  DB 052H
  DB $LNpush$??1Square@@UEAA@XZ-$LNbeg$??1Square@@UEAA@XZ
  DB 050H
  DW 0
.xdata ENDS

.CODE
.text$mn SEGMENT ALIGN(16) 'CODE' COMDAT(??_GSquare@@UEAAPEAXI@Z)
??_GSquare@@UEAAPEAXI@Z PROC
$LNbeg$??_GSquare@@UEAAPEAXI@Z:
  push rbp
$LNpush$??_GSquare@@UEAAPEAXI@Z:
  sub rsp, 48
$LNalloc$??_GSquare@@UEAAPEAXI@Z:
  mov rbp, rsp
$LNfp$??_GSquare@@UEAAPEAXI@Z:
$LNprolog$??_GSquare@@UEAAPEAXI@Z:
  mov rax, rcx
  mov QWORD PTR [rbp+40], rax
  mov rax, rdx
  mov DWORD PTR [rbp+36], eax
  lea rax, [rbp+40]
  mov rax, QWORD PTR [rax]
  push rax
  pop rcx
  mov rax, 0
  call ??1Square@@UEAA@XZ
  mov rax, 1
  push rax
  lea rax, [rbp+36]
  mov eax, DWORD PTR [rax]
  pop r10
  and eax, r10d
  mov eax, eax
  cmp rax, 0
  je $_L_??_GSquare@@UEAAPEAXI@Z_end_0
  lea rax, [rbp+40]
  mov rax, QWORD PTR [rax]
  push rax
  pop rcx
  mov rax, 0
  call ??3@YAXPEAX@Z
$_L_??_GSquare@@UEAAPEAXI@Z_end_0:
  lea rax, [rbp+40]
  mov rax, QWORD PTR [rax]
  jmp $_L_return_??_GSquare@@UEAAPEAXI@Z
  mov rax, 0
$_L_return_??_GSquare@@UEAAPEAXI@Z:
  lea rsp, [rbp+48]
  pop rbp
  ret
$LNend$??_GSquare@@UEAAPEAXI@Z:
??_GSquare@@UEAAPEAXI@Z ENDP
.text$mn ENDS

.pdata SEGMENT READONLY ALIGN(4) 'DATA' ASSOCIATIVE(??_GSquare@@UEAAPEAXI@Z)
$pdata$??_GSquare@@UEAAPEAXI@Z DD imagerel $LNbeg$??_GSquare@@UEAAPEAXI@Z
  DD imagerel $LNend$??_GSquare@@UEAAPEAXI@Z
  DD imagerel $unwind$??_GSquare@@UEAAPEAXI@Z
.pdata ENDS
.xdata SEGMENT READONLY ALIGN(8) 'DATA' ASSOCIATIVE(??_GSquare@@UEAAPEAXI@Z)
$unwind$??_GSquare@@UEAAPEAXI@Z DB 01H
  DB $LNprolog$??_GSquare@@UEAAPEAXI@Z-$LNbeg$??_GSquare@@UEAAPEAXI@Z
  DB 3
  DB 05H
  DB $LNfp$??_GSquare@@UEAAPEAXI@Z-$LNbeg$??_GSquare@@UEAAPEAXI@Z
  DB 03H
  DB $LNalloc$??_GSquare@@UEAAPEAXI@Z-$LNbeg$??_GSquare@@UEAAPEAXI@Z
  DB 052H
  DB $LNpush$??_GSquare@@UEAAPEAXI@Z-$LNbeg$??_GSquare@@UEAAPEAXI@Z
  DB 050H
  DW 0
.xdata ENDS

.CODE

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?fromB@@YAHH@Z$catch$0 DD imagerel $LNbeg$?fromB@@YAHH@Z$catch$0
  DD imagerel $LNend$?fromB@@YAHH@Z$catch$0
  DD imagerel $unwind$?fromB@@YAHH@Z$catch$0
.pdata ENDS

.pdata SEGMENT READONLY ALIGN(4) 'DATA'
$pdata$?fromB@@YAHH@Z$catch$1 DD imagerel $LNbeg$?fromB@@YAHH@Z$catch$1
  DD imagerel $LNend$?fromB@@YAHH@Z$catch$1
  DD imagerel $unwind$?fromB@@YAHH@Z$catch$1
.pdata ENDS

END
